language: python
python:
  - "2.7"
before_install:
  - export PIP_USE_MIRRORS=true
install:
  - pip install -e .
  - pip install -r requirements/tests.txt Django==$DJANGO
before_script:
  - flake8 --exclude=migrations,south_migrations robokassa
script:
  - python runtests.py
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.16
  - DJANGO=1.5.11
  - DJANGO=1.6.8
  - DJANGO=1.7.1
branches:
  only:
    - master
